remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme

title: Oracle SBT for Cloud Storage
description: >
  Oracle SBT for Cloud Storage enables the backup and restoration of Oracle databases to and from cloud storage.

show_downloads: false
